#Python **Basics** (Data types and variables)
There are **three** basic data types in python. They are **Integers**,**Floating point numbers** and **Strings**. Here  is a quick demonstration of these data types

Data types and converting data types

In [ ]:
# Integers
a=10
print(a)
print(type(a))
# Floating point Numbers
b=10.5
print(type(b))
# Strings
c="Hellow world"
print(type(c))

10
<class 'int'>
<class 'float'>
<class 'str'>


# Variable Name and Constrains

You can set almost whatever you want in the variable name. However there are constraints

In [ ]:
# can't set a variable name like this
account balance=100 # can't have spaces
42name="name" # can't start with number
True="laku" # Reserve python words




SyntaxError: ignored

In [ ]:
print()=laku
print()

SyntaxError: ignored

#string operations

In [ ]:
echo="Hellow world. This is my first python code"

In [ ]:
echo.upper()

'HELLOW WORLD. THIS IS MY FIRST PYTHON CODE'

In [ ]:
echo.lower()

'hellow world. this is my first python code'

In [ ]:
echo.startswith('H')

True

In [ ]:
print("i am " + str( 23 ) + " years old")

i am 23 years old


In [ ]:
y= str(x)


In [ ]:
type(y)

str

In [ ]:
age=input("What's your age:")
print("My age is:",age)

What's your age:22
your age is: 22


# Flow Control

In [ ]:
# Boolean values
is_raining= False
not_raining= True

In [ ]:
# if condition
raining= False
if raining:
  print("it's raining. Better not to go out")
else:
  print("It's not raining. We can go out now")

It's not raining. We can go out now


In [ ]:
num=10
guess=int(input("Enter your guess for the number:"))
if guess<num:
  print ("your guess is lower than the number")
elif guess>num:
  print("Your guess is greater than the number")
else:
  print("You just perfectly guess the number")

Enter your guess for the number:10
You just perfectly guess the number


**While Loop**

In [ ]:
total=0
i=0
while i<100:
  total=total+i
  i=i+1
print(total)

4950


In [ ]:
# Continue and break statement
name=input("Enter your name:")
while True:
  if name!="sirso":
    print("access denied and enter again")
    name=input()
    continue
  else:
    print ("access granted. welcome")
  break

Enter your name:laku 
access denied and enter again
sirso 
access denied and enter again
sirso
access granted. welcome


**For loop**

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(10,1,-2):
  print(i)


10
8
6
4
2


**Importing module**

In [ ]:
import random
for i in range(5):
  print(random.randint(1,100))

91
89
61
6
51


In [ ]:
s="integral"
for index,letter in enumerate(s):
  print(letter,index)

i 0
n 1
t 2
e 3
g 4
r 5
a 6
l 7


# Functions

In [ ]:
def welcome(name):
  print("Hello "+ name +". Welcome to Department of Mathematics and Natural Sciences")


In [ ]:
welcome("Sirso")

Hello Sirso. Welcome to Department of Mathematics and Natural Sciences


In [ ]:
def square(x):
  return x*x

In [ ]:
square(5)

25

# Data structure
There are a few build-in data structure a in python. Among them **List** is multifunctional, fast and easily to handle. **List** opens with third bracket.

In [ ]:
a=[10,10,10,10,"laku"]

In [ ]:
a[1::2]

[10, 10]

In [ ]:
fruits=["orange", "banana", "mango", "licchi"]

In [ ]:
for each_item in fruits:
  print(each_item)

orange
banana
mango
licchi


In [ ]:
# Use of random module in a list
random.choice(fruits)

'mango'

**Tuple** are enclosed with first bracket.

In [ ]:
a=(10,56,45, 54,23,10)

In [ ]:
b=(10,5)

In [ ]:
a.count(10)

2

In [ ]:
# Unpacking tuple
x,y=b
x

10

**Dictionaries**

In [ ]:
student_record={
    "name": "sirso",
    "age": 18,
    "birthday": "09/09/1998",
    "grade": 4.00
}

In [ ]:
# Change value of key
student_record["age"]=19

In [ ]:
# Access key value
student_record["age"]

19

In [ ]:
# Print the whole dictionary
student_record

{'name': 'sirso',
 'age': 19,
 'birthday': '09/09/1998',
 'grade': 4.0,
 'id': 1612020}

In [ ]:
# Adding more key-value pair
if "bank_acc" not in student_record:
  student_record["bank_acc"]=440440634
else:
  print("bank_acc is in student record")

In [ ]:
for key in student_record:
  print(key,student_record[key])

name sirso
age 19
birthday 09/09/1998
grade 4.0
id 1612020
bank_acc 440440634


**Set** opens and ends with curly braces.

In [ ]:
# Creating Set
set_A={1,2,3}
set_A.add(3)

In [ ]:
set_A

{1, 2, 3}

In [ ]:
set_B={1,4,5,6}
set_B.discard(5)
set_B


{1, 4, 6}

In [ ]:
# Union of sets
set_A | set_B

{1, 2, 3, 4, 5, 6}

# Error Handling
**try** and **except** is super useful for handling errors in python code.

In [ ]:
try:
  print(1/0)
except :
  print('you should go here')

you should go here


In [ ]:
try:
  print(1/0)
except ZeroDivisionError:
  print('you should go here')

you should go here


In [ ]:
try:
  print(1/0)
except NameError:
  print('you should not go here')

ZeroDivisionError: ignored

# Introduction to Numpy Module

In [ ]:
import numpy as np

In [ ]:
a=np.array([10,20,30])

In [ ]:
b=np.zeros(5)

In [ ]:
b

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
c=np.arange(1,10,2)
c

array([1, 3, 5, 7, 9])

In [ ]:
np.sin(c)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849])

In [ ]:
np.cos(c)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026])

In [ ]:
np.sum(c)

25

In [ ]:
d=np.arange(0,50,1)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
len(d)

50

In [ ]:
e=np.reshape(d,(5,10))

In [ ]:
e.shape

(5, 10)

In [ ]:
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
np.transpose(e)

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])

In [ ]:
e+2

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

#Read More

1. https://automatetheboringstuff.com/
2. https://www.youtube.com/watch?v=_uQrJ0TkZlc&ab_channel=ProgrammingwithMosh
3. https://www.3blue1brown.com/topics/calculus

